BMS mapset install:
CEDA DEFINE MAPSET(ZBANKSET) GROUP(ZBANK)
CEDA INSTALL MAPSET(ZBANKSET) GROUP(ZBANK)

ZBNK transaction install:
CEDA DEFINE TRANSACTION(ZBNK) PROGRAM(ZBNKBANK) GROUP(ZBANK)
CEDA DEFINE PROGRAM(ZBNKBANK) GROUP(ZBANK)
CEDA DEFINE LIBRARY(ZBNKLOAD) GROUP(ZBANK) DSNAME01(U0210.CICS.LOADLIB)
CEDA INSTALL TRANSACTION(ZBNK) GROUP(ZBANK)
CEDA INSTALL PROGRAM(ZBNKBANK) GROUP(ZBANK)
CEDA INSTALL LIBRARY(ZBNKLOAD) GROUP(ZBANK)

Subprogram installs:
CEDA DEFINE PROGRAM(ZBNKAUTH) GROUP(ZBANK)
CEDA INSTALL PROGRAM(ZBNKAUTH) GROUP(ZBANK)
CEDA DEFINE PROGRAM(ZBNKTXN) GROUP(ZBANK)
CEDA INSTALL PROGRAM(ZBNKTXN) GROUP(ZBANK)

VSAM account file install:
CEMT SET FILE(VSAMZBNK) FORCECLOSE
CEDA DELETE FILE(VSAMZBNK) GROUP(ZBANK)
CEDA DEFINE FILE(VSAMZBNK) GROUP(ZBANK) DSNAME(U0210.VSAM.ZBANK) UPDATE(YES) (Without spaces in the filename 'U0210.VSAM.ZBANK', scroll with F8 through the shown screen and check if Browse, Add, Delete are set to YES. You can set all permissions to YES to be safe.)
CEDA INSTALL FILE(VSAMZBNK) GROUP(ZBANK)

VSAM transaction history file install:
CEMT SET FILE(VSAMZBTX) FORCECLOSE
CEDA DELETE FILE(VSAMZBTX) GROUP(ZBANK)
CEDA DEFINE FILE(VSAMZBTX) GROUP(ZBANK) DSNAME(U0210.VSAM.ZBANKTX) UPDATE(YES) (Without spaces in the filename 'U0210.VSAM.ZBANKTX', scroll with F8 through the shown screen and check if Browse, Add, Delete are set to YES.)
CEDA INSTALL FILE(VSAMZBTX) GROUP(ZBANK)
